version: 2

updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  assignees: 
    - alanvardy

  - package-ecosystem: "github-actions"
    directory: "/"  # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - stacksjb
