coverage:
  ignore:
    - src/error.rs
    - src/input.rs
    - src/color.rs
    - src/debug.rs
    - src/main.rs
  status:
    project:
      default:
        target: 50%
        threshold: 0%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 2%
        base: auto
