# This workflow runs on all PRs and ensures they are formatted using Conventional Commits (https://www.conventionalcommits.org/), rejecting any that do not conform to the commit message standards.

name: Commit Lint

on: [pull_request]  

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./.github/workflows/config/commitlint.config.mjs
