name: Release Binaries (macOS and Homebrew)

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with "v" (e.g., v1.0.0)

jobs:
  build:
    name: Build, Release, and Publish for macOS and Homebrew
    runs-on: macos-latest  # Use macOS runner

    strategy:
      matrix:
        architecture: [aarch64, x86_64]  # Architecture matrix for ARM and Intel builds

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up Rust toolchain
    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    # Build for macOS based on matrix architecture
    - name: Build for macOS
      run: |
        echo "Building for macOS ${ARCHITECTURE}"
        cargo build --release --target ${{ matrix.architecture }}-apple-darwin
        echo "Build completed for ${ARCHITECTURE}"
        ls target/release  # List files in the target/release directory to verify output

    # Gzip the binary based on architecture
    - name: Gzipping the binary
      run: |
        ARCHITECTURE=${{ matrix.architecture }}
        OUTPUT_FILE="mac_${ARCHITECTURE}.tar.gz"
        ls target/release/${ARCHITECTURE}-apple-darwin/release/  # Verify the path
        tar -czf target/release/$OUTPUT_FILE target/release/${ARCHITECTURE}-apple-darwin/release/$GITHUB_REPOSITORY
        echo "Created $OUTPUT_FILE"

    # Hash the release binary based on architecture
    - name: Hash release binary
      run: |
        ARCHITECTURE=${{ matrix.architecture }}
        OUTPUT_FILE="mac_${ARCHITECTURE}.tar.gz"
        ls target/release  # Verify the file exists before hashing
        HASH=$(shasum -a 256 target/release/$OUTPUT_FILE | awk '{print $1}')
        echo "${ARCHITECTURE} HASH: $HASH"
    
    # Update Homebrew formula with the new version and hash for both architectures
    - name: Update Homebrew formula
      run: |
        cd ./homebrew-tod  # Ensure you're in the correct directory
        ARCHITECTURE=${{ matrix.architecture }}
        OUTPUT_FILE="mac_${ARCHITECTURE}.tar.gz"
        ambr --regex "version \"\\d+\\.\\d+\\.\\d+\"" "version \"$GITHUB_REF_NAME\"" Formula/tod.rb
        ambr --regex "https://github.com/alanvardy/tod/releases/download/v\d+\\.\\d+\\.\\d+/" "https://github.com/alanvardy/tod/releases/download/v$GITHUB_REF_NAME/" Formula/tod.rb
        ambr --regex "sha256 \"[0-9a-z]+\"" "sha256 \"$HASH\"" Formula/tod.rb
        echo "Homebrew formula updated for ${ARCHITECTURE}"

    # Ensure the branch is up to date with the remote
    - name: Ensure branch is up to date
      run: |
        git fetch origin
        git status
        if ! git status | grep -q "Your branch is up to date with"; then
            echo "Error: The branch is not up-to-date with the remote. Please pull the latest changes before proceeding."
            exit 1
        fi

    # Commit and push Homebrew formula changes
    - name: Commit and push Homebrew changes
      run: |
        git add .
        git commit -m "Release version $GITHUB_REF_NAME"
        git push origin HEAD
        echo "Homebrew update complete"

    # Upload binaries to GitHub release using softprops/action-gh-release
    - name: Upload binaries to GitHub release
      uses: softprops/action-gh-release@v2.2.2
      with:
        files: |
          target/release/mac_${{ matrix.architecture }}.tar.gz
        token: ${{ secrets.RELEASE_PAT }}  # Use RELEASE_PAT token for authentication
