name: Release Check

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, ready_for_review]

jobs:
  check-release-pr:
    name: Check Changelog & Cargo.toml Versions
    if: >
      startsWith(github.head_ref, 'release-please--') ||
      contains(github.event.pull_request.labels.*.name, 'autorelease: pending')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract and compare versions from files
        run: |
          # Extract from CHANGELOG.md
          changelog_version=$(head -n 7 CHANGELOG.md | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+' | head -n 1)
          changelog_version_clean=${changelog_version#*v}
          echo "CHANGELOG: $changelog_version_clean"

          # Extract from Cargo.toml
          cargo_version=$(grep -oP '^version = "\d+\.\d+\.\d+"$' Cargo.toml | sed 's/version = "//g' | sed 's/"//g')
          echo "Cargo.toml: $cargo_version"

          if [[ "$changelog_version_clean" == "$cargo_version" ]]; then
            echo "Versions match: $cargo_version"
          else
            echo "Mismatch: CHANGELOG=$changelog_version_clean, Cargo.toml=$cargo_version"
            exit 1
          fi
